### ISSUE TITLE
Landing page - logic implementation

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#124]
**Objective**
DeWeb branding declines different fonts, colours, and messages. To implement this logic, we use the landing page as a test.
So the objectives are:
* to validate the design rules,
* to test and find the most efficient way to implement the needed code to retrieve the design rules
* to build a landing page on-chain and another one off-chain

**How to**
Design: https://www.figma.com/design/b2ppNK0ZMDXF0gNXyssmHx/Deweb?node-id=0-1&node-type=canvas&t=33okMSOY31ulS29R-0
- [x] Init project https://github.com/massalabs/deweb_home/pull/1
- [x] Init Massa repo https://github.com/massalabs/deweb_home/pull/1
- [x] Decide which FE framework we'll use - tailwind vs. Vanilla 
- [x] Implement the design (+ test the responsiveness) 
- [x] Add mkt wording https://github.com/massalabs/deweb_home/pull/10
- [ ] #150
- [x] Build generative logo algo (Think and decide what is the best way to implement the rules: using SVG or writing code or sth else + decide if we need to create another UI kit or update the existing one (what are the best practices?) etc...)
- [x] Build theme generation https://github.com/massalabs/deweb_home/pull/11
- [x] add visual sugar https://github.com/massalabs/deweb_home/pull/11
- [x] decide what to do when the countdown is over 
- [ ] #149

**Comment by pivilartisant** [comment]
- [X] Init project was done here: https://github.com/pivilartisant/deweb_landing_page

**Comment by pivilartisant** [comment]
@SlnPons concerning tailwind vs vanilla we need so visibility on landing page future -> 

We decided with @thomas-senechal that the technology should be chosen according to the project. 

If the landing page will just be a landing page that doesn't need a lot of changes or maintenance than vanilla css is suitable because the project will have a small scale and will not need to be scalable. 

If we want the landing page to become an "entry point" to the DeWeb than tailwind is more adapted because it is more dev friendly and results in less overall css files.

**Comment by pivilartisant** [comment]
![Image](https://github.com/user-attachments/assets/69962ff1-d14b-408b-9758-365bd909968f)

We are going with tailwind because the landingpage will become a broader homepage

> [@SlnPons](https://github.com/SlnPons) concerning tailwind vs vanilla we need so visibility on landing page future ->
> 
> We decided with [@thomas-senechal](https://github.com/thomas-senechal) that the technology should be chosen according to the project.
> 
> If the landing page doesn't need a lot of changes or maintenance than vanilla css is suitable because the project will have a small scale.
> 
> If we want the landing page to become an "entry point" to the DeWeb than tailwind is more adapted because it allows efficient scaling

**Comment by SlnPons** [comment]
@pivilartisant can you confirm me that we have implemented the infographie in the "about deweb"? I can't remember seeing them. 

And if it's done, could you start to organise user test please? 
I would suggest: text + link for all internal people + kevin & Maria; and 30min meetings w/ Joao.

**Comment by pivilartisant** [comment]
> @pivilartisant can you confirm me that we have implemented the infographie in the "about deweb"? I can't remember seeing them.
> 
> And if it's done, could you start to organise user test please? I would suggest: text + link for all internal people + kevin & Maria; and 30min meetings w/ Joao.

here is the about figure we have right now: 
<img width="998" alt="Screenshot 2024-10-28 at 15 28 59" src="https://github.com/user-attachments/assets/eca1d327-85f7-468d-babc-a8b44b74e821">
