### ISSUE TITLE
Improve cache creation

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/DeWeb#147]
**Context**
Follows https://github.com/massalabs/DeWeb/pull/145#discussion_r1816233390

ATM, we create a new cache struct each time we need it. We could simplify that by having a singleton or having it stored in the API context. 

**Todo**
- [ ] Decide how to store the cache struct 
- [ ] Implement the changes
- [ ] Ensure cache is still working properly

**Comment by SlnPons** [comment]
Hey @thomas-senechal I'm not sure to understand the objective of this issue or what it solves. Could you elaborate please?

**Comment by thomas-senechal** [comment]
> Hey @thomas-senechal I'm not sure to understand the objective of this issue or what it solves. Could you elaborate please?

It's a technical issue, would make the code a tiny bit cleaner and improve a very little performances 

Not a priority IMO

**Comment by thomas-senechal** [comment]
Note that we are talking of a dozens of nano seconds, so really not a priority

**Comment by thomas-senechal** [comment]
Done with #277 :)))
