### ISSUE TITLE
Improve uploader front-end

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/DeWeb#168]
- [x] Fork current DeWeb Home Page repo to create an isolated dev environnment 
- [X] Add wallet connect
- [x] Add Deploy SC for [bearby](https://github.com/massalabs/wallet-provider/pull/261) and [MassaStation](https://github.com/massalabs/DeWeb/issues/174)
- [x] Add upload progression states
- [x] Add upload progression loader
- [x] Add network status (so users don't accidentally upload on mainnet) 
- [x] Refactor interface using material ui to look like this: https://github.com/massalabs/DeWeb/issues/168#issuecomment-2483448256

**Comment by pivilartisant** [comment]
working on this branch for now: https://github.com/massalabs/deweb_home/pull/22

**Comment by pivilartisant** [comment]
dependancy: https://github.com/massalabs/DeWeb/issues/174
