### ISSUE TITLE
Deploy Index SC on Mainnet

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/DeWeb#188]
**Context**
ATM, the DeWeb index SC has only been deployed on Buildnet. We need to deploy it on mainnet before releasing DeWeb.

**TODO**
- [ ] Request access to a mainnet wallet 
- [ ] Deploy the SC
- [ ] Add existing DeWeb websites to the Index

**Comment by SlnPons** [comment]
Note: mainnet mkt launch is planned on Jan 15th

**Comment by SlnPons** [comment]
@thomas-senechal is this done?

**Comment by thomas-senechal** [comment]
Yep, done here https://github.com/massalabs/DeWeb/issues/214 
Looks like we had a duplicated issue
