### ISSUE TITLE
Implement SC upgrade command

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/DeWeb#189]
**Context**
We will need a command to upgrade an existing DeWeb SC.

**TODO**

- [ ] Get the deployed SC bytecode
- [ ] Compare the SC bytecode with the wasm in the CLI
- [ ] If not the same, upgrade it using the `upgradeSC` function
