### ISSUE TITLE
Call updateWebsite index after deploying a DeWeb SC

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/DeWeb#190]
**Context**
Now that the DeWeb Index V1 is done (and deployed on buildnet), we can use it to add websites to it.

**TODO**

- [x] Make a function that calls `updateWebsite` of DeWeb Index
- [x] Prepare Buildnet/Mainnet handling
- [x] Use the created function after deploy to register the SC
