### ISSUE TITLE
Remake WebsiteStorer SC

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/DeWeb#91]
**Context**
Following this discussion, we need to remake the SC to match the needs. 
https://forum.massa.community/t/community-feedback-proposal-for-improving-website-storage-on-deweb/82

## Feature
- [x] Upload project
- [x] #118
- [x] Update/upload project metadata and per-file metadata
    - [x] Upload per-file metadata
    - [x] Upload project metadata
    - [x] Remove per-file metadata
    - [x] Remove project metadata
- [x] #116
- [x] Retrieve file chunks
- [x] Retrieve file list
- [x] #120
## Security Concerns
- Verify owner can't cheat, for example by modifying un chunk if immutable or the last update
